version: "3.9"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx-prod
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    ports:
      - 8080:80
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfile-php-prod
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
    expose:
      - 9000
