version: "3.9"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx-prod
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    ports:
      - ${EXPOSE_PORT}:80
    depends_on:
      - php
  php:
    pull_policy: build
    image: php-nginx-php:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile-php-prod
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
    environment:
      - VERSION=${VERSION}
    expose:
      - 9000
